### ISSUE TITLE
Irregular time sampling question

### ISSUE THREAD

**Issue by yhl48** [lindermanlab/S5#13]
Thanks for the amazing paper, I have a technical question about the paper: if a dataset contains samples with irregular time sampling, and the irregularity is not consistent across samples, i.e. sample 1 could be sampled at different timepoints compared to sample 2, would S5 be able to model the data well?

**Comment by andrewwarrington** [comment]
Hi there, yes, irregular sets of irregularly sampled data are supported!  

This application is demonstrated in the `pendulum` branch (we kept it separate because the code gets a bit bloated, and we wanted to keep the core code as simple as possible).

In the dataloader, the observation intervals are batched and returned (see [here](https://github.com/lindermanlab/S5/blob/52cc7e22d6963459ad99a8674e4d3cfb0a480008/s5/dataloading.py#L417)), and we discretize the SSM accordingly [here](https://github.com/lindermanlab/S5/blob/52cc7e22d6963459ad99a8674e4d3cfb0a480008/s5/ssm.py#L319).

I'll close this issue for now, but feel free to re-open it if this isn't sufficient! :)
